language: dart

before_install:
  - chmod +x ./tool/coveralls.sh
  
before_script:
  - pub run build_runner build

dart:
- stable
- dev

dart_task:
- test
- dartanalyzer: --fatal-warnings lib
- dartfmt

after_success: ./tool/coveralls.sh
